env:
    DEVICE_CODENAME: rosy
    BUILD_USER: rosy
    BUILD_HOST: nfs-projects
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: "https://github.com/NFS-Project/AnyKernel3.git"
    TG_TOKEN: "ENCRYPTED[9bf5b7c2dddef79f5f33327db3702b2860436c02ef1b49a84a00af9d80ff177a7966ec899b4343f1ddcc484d933c0250]"
    TG_CHAT_ID: "ENCRYPTED[f9a7f3ce904073ae5d595a4a673a783c67aef3d9fd2bb4bb0ebe6ea8272b51f42c7281586444c33dc052d51ae3500576]"

task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Sync_script:
      - ./download.sh

  Build_kernel_Clang_script:
      - ./clang.sh
      - ./rm.sh

  Notif_script:
      - ./done.sh
