env:
    DEVICE_CODENAME: mido
    BUILD_USER: Rasyid
    BUILD_HOST: RasyidAlKautsar
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: "ENCRYPTED[714d28db47c375058945b8d323018b30653959617dbd6cc17aaf16b33d124ad13e714bc0fae0bfbaec5c4842dd8589f2]"
    TG_TOKEN: "ENCRYPTED[2fbf521fbdb4da1379b6754073a7b3c39d3e5883d58a6529c678fd7a14fe187e1b06538210fefb8fae0e1df84333be9b]"
    TG_CHAT_ID: "ENCRYPTED[6690556fbdba90304bdfbebe4d4a71538f1e27555659cd872048da12d6c13d4fc23aaa8ea30f80332d7cad85efbcc411]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Sync_script:
      - ./download.sh

  Build_kernel_Clang_script:
      - ./clang.sh
      - ./rm.sh

  Build_kernel_GCC_11_script:
      - ./gcc.sh
      - ./rm.sh

  Build_kernel_GCC_12_script:
      - ./gcc12.sh
      - ./rm.sh

  Notif_script:
      - ./done.sh
