env:
    DEVICE_CODENAME: mido
    BUILD_USER: Rasyid
    BUILD_HOST: RasyidAlKautsar
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: "ENCRYPTED[714d28db47c375058945b8d323018b30653959617dbd6cc17aaf16b33d124ad13e714bc0fae0bfbaec5c4842dd8589f2]"
    TG_TOKEN: "ENCRYPTED[a5508dfc660c455d16afd511565ed72dbbe880ebe7cc5de1ac302fd5b282900e17f4a48d817745b699751a1b07101eda]"
    TG_CHAT_ID: "ENCRYPTED[5ecfaae8500ed2634e9b59a965f4c1474c62d51a5a4d8334a5a2cc18b44fc392321eca90c62709bd3d147cbae774bdcd]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Sync_script:
      - ./download.sh

  Build_kernel_Clang_script:
      - ./clang.sh
      - ./rm.sh

  Build_kernel_GCC_11_script:
      - ./gcc.sh
      - ./rm.sh

  Build_kernel_GCC_12_script:
      - ./gcc12.sh
      - ./rm.sh

  Notif_script:
      - ./done.sh
