env:
    DEVICE_CODENAME: rosy
    BUILD_USER: rosy
    BUILD_HOST: nfs-project
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: "ENCRYPTED[714d28db47c375058945b8d323018b30653959617dbd6cc17aaf16b33d124ad13e714bc0fae0bfbaec5c4842dd8589f2]"
    TG_TOKEN: "ENCRYPTED[4b71b825ca6ea1c5ba7ddc6fc7e244dfaf97b00890ccf9d84ef11b7f812369eac740e48ceb42842d971271656de706c1]"
    TG_CHAT_ID: "ENCRYPTED[2adb4341b5d697a505cc2075c85736c5459e03852a55b8acb3df68a8eaeec80b6d857f7addbdced87ac5fb035fba8197]"

task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Sync_script:
      - ./download.sh

  Build_kernel_Clang_script:
      - ./clang.sh
