env:
    DEVICE_CODENAME: rosy
    BUILD_USER: rosy
    BUILD_HOST: nfs-project
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: "https://github.com/NFS-Project/AnyKernel3.git"
    TG_TOKEN: "ENCRYPTED[d4b549524faa62079bed2ee41fa017fab9f90ecea504cf27762821d9c8a8092ce7f175863252fdb6a9a23063d90ce11b]"
    TG_CHAT_ID: "ENCRYPTED[7e2a4214fedb42d840ed0be87ae69152aa17e58adb6e5915141ce22f8a9efb3f507bc297b38bab685d9e69b35de44f2f]"

task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Sync_script:
      - ./download.sh

  Build_kernel_Clang_script:
      - ./clang.sh
